"""empty message

Revision ID: 800595f15632
Revises: 
Create Date: 2020-08-20 12:07:43.356350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800595f15632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=10), nullable=True),
    sa.Column('tile_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('columns', sa.String(length=5), nullable=True),
    sa.Column('rows', sa.String(length=5), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('images', sa.Integer(), nullable=True),
    sa.Column('files', sa.Integer(), nullable=True),
    sa.Column('links', sa.Integer(), nullable=True),
    sa.Column('videos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tile_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('border', sa.String(length=255), nullable=True),
    sa.Column('filters', sa.String(length=255), nullable=True),
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile_styles')
    op.drop_table('element')
    op.drop_table('user')
    op.drop_table('tile')
    op.drop_table('global_role')
    # ### end Alembic commands ###
